INSERT INTO country (id, name) VALUES
('tR9uehn2c8', 'Afganistán'),
('wEcvnEmqKE', 'Albania'),
('gfnTxnbcK2', 'Alemania'),
('jXsNOH0rHx', 'Andorra'),
('lInx9AQ7jH', 'Angola'),
('bMslgLX62w', 'Antigua y Barbuda'),
('Keevwx9Ycw', 'Arabia Saudita'),
('Ge4dm4h1It', 'Argelia'),
('wj7Semu7A4', 'Argentina'),
('3E6QRTqsU3', 'Armenia'),
('d4aHTTw6eN', 'Australia'),
('w2f0IVHf0o', 'Austria'),
('C31OXH3w11', 'Azerbaiyán'),
('Cie7OYgVPB', 'Bahamas'),
('3Bpm4r6S6A', 'Bangladés'),
('d-1lhAe5_8', 'Barbados'),
('_YKetAfgWd', 'Baréin'),
('IeJHCv0JTj', 'Bélgica'),
('8dQUBbJ1Bl', 'Belice'),
('5TpzoogyFA', 'Benín'),
('g30Nxi5bJe', 'Bielorrusia'),
('1vG0Sm1N3A', 'Birmania'),
('BU496vYz-_', 'Bolivia'),
('BHiE1GKMJ6', 'Bosnia y Herzegovina'),
('dFPxoxIjdO', 'Botsuana'),
('6eDRQz_EfP', 'Brasil'),
('6CibnINMaE', 'Brunéi'),
('bWq3UoAKeG', 'Bulgaria'),
('7QkXPPMUQY', 'Burkina Faso'),
('S3xVQ9skuE', 'Burundi'),
('vuqisPtEWK', 'Bután'),
('NRueF92eLF', 'Cabo Verde'),
('Zb2Ig06VDi', 'Camboya'),
('JOanVVezoK', 'Camerún'),
('fXxBt6KYXu', 'Canadá'),
('Wx3vE6ewI9', 'Catar'),
('NA55WW5Z1f', 'Chad'),
('94y8Bc8cHe', 'Chile'),
('IRlKwrOAxp', 'China'),
('aHC7RIYzuN', 'Chipre'),
('IQVkP2-M8X', 'Ciudad del Vaticano'),
('fOCOii9rU-', 'Colombia'),
('3D3iXwkqYX', 'Comoras'),
('FOQQ6QA1zW', 'Corea del Norte'),
('muZUjCCbLP', 'Corea del Sur'),
('Md-UagHhlC', 'Costa de Marfil'),
('7gAQFslliJ', 'Costa Rica'),
('UTYmyEmcKq', 'Croacia'),
('xu-pDqZkdj', 'Cuba'),
('UkuDHiYcPq', 'Dinamarca'),
('wAb43PPgUo', 'Dominica'),
('2fHE2EM9Mp', 'Ecuador'),
('BlrHeSwoP-', 'Egipto'),
('HlptVHC687', 'El Salvador'),
('n5rZ9CcgAI', 'Emiratos Árabes Unidos'),
('leO0OX1jv2', 'Eritrea'),
('9eFtMoO-U5', 'Eslovaquia'),
('xav0Wla7DR', 'Eslovenia'),
('pPIwuDh5Vj', 'España'),
('UPyjgzBZhX', 'Estados Unidos'),
('2hIFyrHgbq', 'Estonia'),
('OJZyEKQSG6', 'Etiopía'),
('jbvEBodgic', 'Filipinas'),
('2XQK1Fd7FU', 'Finlandia'),
('QWl_YdeOMQ', 'Fiyi'),
('ZK8pp5TJgI', 'Francia'),
('eIMxu_NhTg', 'Gabón'),
('BD7aNcCuKT', 'Gambia'),
('ktGPynp2qF', 'Georgia'),
('d9J6sNGAYQ', 'Ghana'),
('2rkektAyID', 'Granada'),
('CRbIMnwmw0', 'Grecia'),
('MyNza1lh59', 'Guatemala'),
('l2tGpxFgpU', 'Guinea'),
('Jef0w3u02n', 'Guinea-Bisáu'),
('odwiWzZA0_', 'Guinea Ecuatorial'),
('XxFaIIgbBK', 'Guyana'),
('Y7qZlPJbwq', 'Haití'),
('f7B0FJ8fMD', 'Honduras'),
('G7UGP5C-7s', 'Hungría'),
('olerczpiu_', 'India'),
('oNZaDHO7ex', 'Indonesia'),
('5wc02b62hv', 'Irak'),
('2YmLjvF2jn', 'Irán'),
('06V5FjvNm5', 'Irlanda'),
('pT9xeFGpY1', 'Islandia'),
('t6rrxzKVFk', 'Islas Marshall'),
('sf9dxxMH_Y', 'Islas Salomón'),
('f4O9lEEIgC', 'Israel'),
('ww97MWKyn0', 'Italia'),
('5-EWkVNStC', 'Jamaica'),
('DfO4C9e8yT', 'Japón'),
('L5kU2MsN6w', 'Jordania'),
('3cR_zyvKBp', 'Kazajistán'),
('Wd39DdKPJG', 'Kenia'),
('2baYxW_J8x', 'Kirguistán'),
('z-Q2mX-gco', 'Kiribati'),
('pBqUmQ8jVa', 'Kuwait'),
('Vs5eySlw-V', 'Laos'),
('8wsqdwRzKy', 'Lesoto'),
('NQlHzaV2y0', 'Letonia'),
('XyMhF-4bNv', 'Líbano'),
('UPOazPiPo2', 'Liberia'),
('J5QQsTUABh', 'Libia'),
('sxa4dEtC02', 'Liechtenstein'),
('JwgBTUx27y', 'Lituania'),
('M9C2Qp8A6f', 'Luxemburgo'),
('QEOhS6AGk3', 'Macedonia del Norte'),
('a1x1_qnjbF', 'Madagascar'),
('xCkrc3EJJo', 'Malasia'),
('7erC-241yW', 'Malaui'),
('upqpgM_3rk', 'Maldivas'),
('Hww-Sh90jD', 'Malí'),
('xUYDDSDsSH', 'Malta'),
('zDYjwcXpK_', 'Marruecos'),
('ilR2MvVtFX', 'Mauricio'),
('VX9I_yXi1C', 'Mauritania'),
('G204H25Rfg', 'México'),
('MiqxpNjjMb', 'Micronesia'),
('_Aj8LDhfur', 'Moldavia'),
('3RiP_Bq3Pi', 'Mónaco'),
('v5JEmlkTgD', 'Mongolia'),
('1YXkte0C89', 'Montenegro'),
('3HdERkT-QY', 'Mozambique'),
('PFPD6rI4y2', 'Namibia'),
('EJz5UBqHhe', 'Nauru'),
('qpoK-HN4qG', 'Nepal'),
('p4mRdPBYQ0', 'Nicaragua'),
('PygP5QY-Ya', 'Níger'),
('If9jzTJ3dl', 'Nigeria'),
('W5S7DyrV4C', 'Noruega'),
('egjXKyCw6B', 'Nueva Zelanda'),
('Px0_zNtAar', 'Omán'),
('A0yandR0tP', 'Países Bajos'),
('7QrOAWSe2G', 'Pakistán'),
('OPc-USfOXR', 'Palaos'),
('ZZUzdXniOR', 'Panamá'),
('CQxdZTHmQm', 'Papúa Nueva Guinea'),
('-Pxdbvfvac', 'Paraguay'),
('WdWQupvpVQ', 'Perú'),
('g2IKzq1BOB', 'Polonia'),
('XBcqa-C790', 'Portugal'),
('8uPYA3Zr6t', 'Reino Unido'),
('yZK5M9nfgU', 'República Centroafricana'),
('X7RPQSffYl', 'República Checa'),
('ehSrJkWCm2', 'República del Congo'),
('jo9DkKYD4y', 'República Democrática del Congo'),
('iYNcVGDxpa', 'República Dominicana'),
('Gsmg0s2wZJ', 'Ruanda'),
('q-aTaYb6tX', 'Rumanía'),
('n3UCnBgwbw', 'Rusia'),
('ZvcvjQ-9xA', 'Samoa'),
('_czNNLnmZX', 'San Cristóbal y Nieves'),
('ak6xWcXoXA', 'San Marino'),
('6OlM2ozgfk', 'San Vicente y las Granadinas'),
('TqfdLKBvC2', 'Santa Lucía'),
('1eSvfvnlBN', 'Santo Tomé y Príncipe'),
('brGowo4_IQ', 'Senegal'),
('-g33folrC4', 'Serbia'),
('sIFOI1H4Gc', 'Seychelles'),
('5XJSI8yegV', 'Sierra Leona'),
('FhAyVpccdh', 'Singapur'),
('fw242wTuRf', 'Siria'),
('IX6k8OKQ8Y', 'Somalia'),
('XeSv3963vg', 'Sri Lanka'),
('631NeIk1xb', 'Suazilandia'),
('B9WJIAZX2g', 'Sudáfrica'),
('Qgi-umil0K', 'Sudán'),
('2rgJ8QT-bB', 'Sudán del Sur'),
('r0V8I9NCCO', 'Suecia'),
('UDCxiEAuaa', 'Suiza'),
('J157NIs19b', 'Surinam'),
('ahipCk8lH2', 'Tailandia'),
('eP90rxyCeI', 'Taiwán'),
('2fYmKkkrPN', 'Tanzania'),
('sAZfHVBlU0', 'Tayikistán'),
('ob63UAvTJS', 'Timor Oriental'),
('Tf1AMgRqwq', 'Togo'),
('ndvu-oqLpf', 'Tonga'),
('PLQnNx7aq5', 'Trinidad y Tobago'),
('MkpuvYOvPe', 'Túnez'),
('_DHH0bLOdY', 'Turkmenistán'),
('Ku_y2VLGHC', 'Turquía'),
('ZOVi0JXQOs', 'Tuvalu'),
('TAfyaSP_N8', 'Ucrania'),
('V6HAfoOzGL', 'Uganda'),
('eII7OFDTXz', 'Uruguay'),
('25LnNKUYGl', 'Uzbekistán'),
('8JCFHjNwze', 'Vanuatu'),
('blCr0vNXEo', 'Venezuela'),
('E3G2HRl9x2', 'Vietnam'),
('5DpYL7MSd-', 'Yemen'),
('wF87FpoWE0', 'Yibuti'),
('35zloN61lw', 'Zambia'),
('WyYBuP37Ps', 'Zimbabue');