INSERT INTO language (name) VALUES
('Alemán'),
('Amárico'),
('Árabe argelino'),
('Árabe egipcio'),
('Árabe estándar moderno'),
('Árabe sudanés'),
('Bengalí'),
('Bhoshpuri'),
('Birmano'),
('Canarés'),
('Chino hakka'),
('Chino jin'),
('Chino mandarín'),
('Chino Mǐn Nán'),
('Chino Wu'),
('Chino yue (incluye Cantonés)'),
('Coreano'),
('Español'),
('Francés'),
('Guyarati'),
('Hausa'),
('Indonesio'),
('Indostánico (hindi estándar, urdu)'),
('Inglés'),
('Italiano'),
('Japonés'),
('Javanés'),
('Lingala'),
('Maratí'),
('Panyabí occidental'),
('Panyabí'),
('Persa iraní'),
('Polaco'),
('Portugués'),
('Ruso'),
('Suajili'),
('Tagalo'),
('Tailandés'),
('Tamil'),
('Telugú'),
('Turco'),
('Urdu'),
('Vietnamita'),
('Yoruba');