INSERT INTO it_field (name) VALUES
('Administración de Bases de Datos'),
('Análisis de Datos'),
('Análsis funcional'),
('Blockchain'),
('Ciberseguridad'),
('Ciencia de Datos'),
('Computación en la nube'),
('Desarrollo de Aplicaciones de Escritorio'),
('Desarrollo de videojuegos'),
('Desarrollo Móvil'),
('Desarrollo Web Backend'),
('Desarrollo Web Frontend'),
('Desarrollo Web FullStack'),
('DevOps'),
('Diseño UX/UI'),
('Gestión de proyectos'),
('Inteligencia artificial'),
('Machine Learning'),
('QC/QA'),
('Redes'),
('Web Scraping');