INSERT INTO it_field (id, name) VALUES
('MDfP4QzwC8', 'Administración de Bases de Datos'),
('yKQuA2BRIs', 'Análisis de Datos'),
('cj_c51MU8R', 'Análsis funcional'),
('u4n-DcV75D', 'Blockchain'),
('Xhr_B_r60R', 'Ciberseguridad'),
('dd0n-1hzJv', 'Ciencia de Datos'),
('4LgM1z9vVK', 'Computación en la nube'),
('SSU0qrs0Vf', 'Desarrollo de Aplicaciones de Escritorio'),
('FNONFwGW2-', 'Desarrollo de videojuegos'),
('38Rv9pG9nd', 'Desarrollo Móvil'),
('ptd-PqQcOU', 'Desarrollo Web Backend'),
('u4zNpNblrn', 'Desarrollo Web Frontend'),
('8XC3UrEWtq', 'Desarrollo Web FullStack'),
('tR2N5r2BpL', 'DevOps'),
('L1QDjzwdHM', 'Diseño UX/UI'),
('VJNrSbFNbH', 'Gestión de proyectos'),
('ZNnhHga0-z', 'Inteligencia artificial'),
('qlHDp52sF_', 'Machine Learning'),
('fsvtQsinbU', 'QC/QA'),
('5-l1cCC4vu', 'Redes'),
('-Ofa7YVQ6I', 'Web Scraping');