INSERT INTO language (id, name) VALUES
('R0mTsUhxr_', 'Alemán'),
('pF3yNwyvis', 'Amárico'),
('8QplyXt3or', 'Árabe argelino'),
('nybjGdYiKP', 'Árabe egipcio'),
('pvTY65u5-l', 'Árabe estándar moderno'),
('VxKW7DPjz4', 'Árabe sudanés'),
('cpBgC99lzo', 'Bengalí'),
('rJY_k7sZPe', 'Bhoshpuri'),
('klHT2DSTYG', 'Birmano'),
('BZLqWY-kmi', 'Canarés'),
('A76fSZhEes', 'Chino hakka'),
('PTs7tkOs9c', 'Chino jin'),
('at4hZ1EG-y', 'Chino mandarín'),
('ejmGm9FlBK', 'Chino Mǐn Nán'),
('JQwzG0gpzS', 'Chino Wu'),
('ctJPVLrsSW', 'Chino yue (incluye Cantonés)'),
('f9Xd80Af_v', 'Coreano'),
('GmF16qvoh5', 'Español'),
('zMnto3e8tN', 'Francés'),
('QbeKU1nXg4', 'Guyarati'),
('KRdZHUPyV7', 'Hausa'),
('oC9n3BurDY', 'Indonesio'),
('l9lAYRxFq4', 'Indostánico (hindi estándar, urdu)'),
('2to_l2lsq-', 'Inglés'),
('cWUxjmxWuM', 'Italiano'),
('HQlxuZdUb7', 'Japonés'),
('8yW7-EK3fq', 'Javanés'),
('0yXLxz027G', 'Lingala'),
('opjokJNYpt', 'Maratí'),
('7_9RTrEjbu', 'Panyabí occidental'),
('SqBJIXvs5J', 'Panyabí'),
('KTMDL1OZsZ', 'Persa iraní'),
('vyBj23iw-D', 'Polaco'),
('GqaQOGgr6H', 'Portugués'),
('YNHPpIUyN0', 'Ruso'),
('8KJAd3f2Wz', 'Suajili'),
('Tvu2iNrslT', 'Tagalo'),
('RhI2eEE46m', 'Tailandés'),
('QlWHkAota6', 'Tamil'),
('qi_Lfq3fHz', 'Telugú'),
('2xgA55Im1G', 'Turco'),
('YDP0tpfKSM', 'Urdu'),
('8Oc06O8lCU', 'Vietnamita'),
('f0cZqOx-Lt', 'Yoruba');