INSERT INTO aspect_type (id, name) VALUES
('pOcG-XWN58', 'Publicación'),
('m6udpXPOt6', 'Comentario');

INSERT INTO category (id, name) VALUES
('S5L4FfEnjz', 'Proyectos grupales'),
('L1w-xYdnDH', 'Hojas de vida'),
('X9lWwZFUMs', 'Portafolios'),
('vq8EkwRM5Q', 'Ofertas de trabajo'),
('xOnWXzDLgx', 'Grupos de estudio'),
('WsMK91X7dK', 'Sugerencias de cursos');

INSERT INTO country (id, name) VALUES
('tR9uehn2c8', 'Afganistán'),
('wEcvnEmqKE', 'Albania'),
('gfnTxnbcK2', 'Alemania'),
('jXsNOH0rHx', 'Andorra'),
('lInx9AQ7jH', 'Angola'),
('bMslgLX62w', 'Antigua y Barbuda'),
('Keevwx9Ycw', 'Arabia Saudita'),
('Ge4dm4h1It', 'Argelia'),
('wj7Semu7A4', 'Argentina'),
('3E6QRTqsU3', 'Armenia'),
('d4aHTTw6eN', 'Australia'),
('w2f0IVHf0o', 'Austria'),
('C31OXH3w11', 'Azerbaiyán'),
('Cie7OYgVPB', 'Bahamas'),
('3Bpm4r6S6A', 'Bangladés'),
('d-1lhAe5_8', 'Barbados'),
('_YKetAfgWd', 'Baréin'),
('IeJHCv0JTj', 'Bélgica'),
('8dQUBbJ1Bl', 'Belice'),
('5TpzoogyFA', 'Benín'),
('g30Nxi5bJe', 'Bielorrusia'),
('1vG0Sm1N3A', 'Birmania'),
('BU496vYz-_', 'Bolivia'),
('BHiE1GKMJ6', 'Bosnia y Herzegovina'),
('dFPxoxIjdO', 'Botsuana'),
('6eDRQz_EfP', 'Brasil'),
('6CibnINMaE', 'Brunéi'),
('bWq3UoAKeG', 'Bulgaria'),
('7QkXPPMUQY', 'Burkina Faso'),
('S3xVQ9skuE', 'Burundi'),
('vuqisPtEWK', 'Bután'),
('NRueF92eLF', 'Cabo Verde'),
('Zb2Ig06VDi', 'Camboya'),
('JOanVVezoK', 'Camerún'),
('fXxBt6KYXu', 'Canadá'),
('Wx3vE6ewI9', 'Catar'),
('NA55WW5Z1f', 'Chad'),
('94y8Bc8cHe', 'Chile'),
('IRlKwrOAxp', 'China'),
('aHC7RIYzuN', 'Chipre'),
('IQVkP2-M8X', 'Ciudad del Vaticano'),
('fOCOii9rU-', 'Colombia'),
('3D3iXwkqYX', 'Comoras'),
('FOQQ6QA1zW', 'Corea del Norte'),
('muZUjCCbLP', 'Corea del Sur'),
('Md-UagHhlC', 'Costa de Marfil'),
('7gAQFslliJ', 'Costa Rica'),
('UTYmyEmcKq', 'Croacia'),
('xu-pDqZkdj', 'Cuba'),
('UkuDHiYcPq', 'Dinamarca'),
('wAb43PPgUo', 'Dominica'),
('2fHE2EM9Mp', 'Ecuador'),
('BlrHeSwoP-', 'Egipto'),
('HlptVHC687', 'El Salvador'),
('n5rZ9CcgAI', 'Emiratos Árabes Unidos'),
('leO0OX1jv2', 'Eritrea'),
('9eFtMoO-U5', 'Eslovaquia'),
('xav0Wla7DR', 'Eslovenia'),
('pPIwuDh5Vj', 'España'),
('UPyjgzBZhX', 'Estados Unidos'),
('2hIFyrHgbq', 'Estonia'),
('OJZyEKQSG6', 'Etiopía'),
('jbvEBodgic', 'Filipinas'),
('2XQK1Fd7FU', 'Finlandia'),
('QWl_YdeOMQ', 'Fiyi'),
('ZK8pp5TJgI', 'Francia'),
('eIMxu_NhTg', 'Gabón'),
('BD7aNcCuKT', 'Gambia'),
('ktGPynp2qF', 'Georgia'),
('d9J6sNGAYQ', 'Ghana'),
('2rkektAyID', 'Granada'),
('CRbIMnwmw0', 'Grecia'),
('MyNza1lh59', 'Guatemala'),
('l2tGpxFgpU', 'Guinea'),
('Jef0w3u02n', 'Guinea-Bisáu'),
('odwiWzZA0_', 'Guinea Ecuatorial'),
('XxFaIIgbBK', 'Guyana'),
('Y7qZlPJbwq', 'Haití'),
('f7B0FJ8fMD', 'Honduras'),
('G7UGP5C-7s', 'Hungría'),
('olerczpiu_', 'India'),
('oNZaDHO7ex', 'Indonesia'),
('5wc02b62hv', 'Irak'),
('2YmLjvF2jn', 'Irán'),
('06V5FjvNm5', 'Irlanda'),
('pT9xeFGpY1', 'Islandia'),
('t6rrxzKVFk', 'Islas Marshall'),
('sf9dxxMH_Y', 'Islas Salomón'),
('f4O9lEEIgC', 'Israel'),
('ww97MWKyn0', 'Italia'),
('5-EWkVNStC', 'Jamaica'),
('DfO4C9e8yT', 'Japón'),
('L5kU2MsN6w', 'Jordania'),
('3cR_zyvKBp', 'Kazajistán'),
('Wd39DdKPJG', 'Kenia'),
('2baYxW_J8x', 'Kirguistán'),
('z-Q2mX-gco', 'Kiribati'),
('pBqUmQ8jVa', 'Kuwait'),
('Vs5eySlw-V', 'Laos'),
('8wsqdwRzKy', 'Lesoto'),
('NQlHzaV2y0', 'Letonia'),
('XyMhF-4bNv', 'Líbano'),
('UPOazPiPo2', 'Liberia'),
('J5QQsTUABh', 'Libia'),
('sxa4dEtC02', 'Liechtenstein'),
('JwgBTUx27y', 'Lituania'),
('M9C2Qp8A6f', 'Luxemburgo'),
('QEOhS6AGk3', 'Macedonia del Norte'),
('a1x1_qnjbF', 'Madagascar'),
('xCkrc3EJJo', 'Malasia'),
('7erC-241yW', 'Malaui'),
('upqpgM_3rk', 'Maldivas'),
('Hww-Sh90jD', 'Malí'),
('xUYDDSDsSH', 'Malta'),
('zDYjwcXpK_', 'Marruecos'),
('ilR2MvVtFX', 'Mauricio'),
('VX9I_yXi1C', 'Mauritania'),
('G204H25Rfg', 'México'),
('MiqxpNjjMb', 'Micronesia'),
('_Aj8LDhfur', 'Moldavia'),
('3RiP_Bq3Pi', 'Mónaco'),
('v5JEmlkTgD', 'Mongolia'),
('1YXkte0C89', 'Montenegro'),
('3HdERkT-QY', 'Mozambique'),
('PFPD6rI4y2', 'Namibia'),
('EJz5UBqHhe', 'Nauru'),
('qpoK-HN4qG', 'Nepal'),
('p4mRdPBYQ0', 'Nicaragua'),
('PygP5QY-Ya', 'Níger'),
('If9jzTJ3dl', 'Nigeria'),
('W5S7DyrV4C', 'Noruega'),
('egjXKyCw6B', 'Nueva Zelanda'),
('Px0_zNtAar', 'Omán'),
('A0yandR0tP', 'Países Bajos'),
('7QrOAWSe2G', 'Pakistán'),
('OPc-USfOXR', 'Palaos'),
('ZZUzdXniOR', 'Panamá'),
('CQxdZTHmQm', 'Papúa Nueva Guinea'),
('-Pxdbvfvac', 'Paraguay'),
('WdWQupvpVQ', 'Perú'),
('g2IKzq1BOB', 'Polonia'),
('XBcqa-C790', 'Portugal'),
('8uPYA3Zr6t', 'Reino Unido'),
('yZK5M9nfgU', 'República Centroafricana'),
('X7RPQSffYl', 'República Checa'),
('ehSrJkWCm2', 'República del Congo'),
('jo9DkKYD4y', 'República Democrática del Congo'),
('iYNcVGDxpa', 'República Dominicana'),
('Gsmg0s2wZJ', 'Ruanda'),
('q-aTaYb6tX', 'Rumanía'),
('n3UCnBgwbw', 'Rusia'),
('ZvcvjQ-9xA', 'Samoa'),
('_czNNLnmZX', 'San Cristóbal y Nieves'),
('ak6xWcXoXA', 'San Marino'),
('6OlM2ozgfk', 'San Vicente y las Granadinas'),
('TqfdLKBvC2', 'Santa Lucía'),
('1eSvfvnlBN', 'Santo Tomé y Príncipe'),
('brGowo4_IQ', 'Senegal'),
('-g33folrC4', 'Serbia'),
('sIFOI1H4Gc', 'Seychelles'),
('5XJSI8yegV', 'Sierra Leona'),
('FhAyVpccdh', 'Singapur'),
('fw242wTuRf', 'Siria'),
('IX6k8OKQ8Y', 'Somalia'),
('XeSv3963vg', 'Sri Lanka'),
('631NeIk1xb', 'Suazilandia'),
('B9WJIAZX2g', 'Sudáfrica'),
('Qgi-umil0K', 'Sudán'),
('2rgJ8QT-bB', 'Sudán del Sur'),
('r0V8I9NCCO', 'Suecia'),
('UDCxiEAuaa', 'Suiza'),
('J157NIs19b', 'Surinam'),
('ahipCk8lH2', 'Tailandia'),
('eP90rxyCeI', 'Taiwán'),
('2fYmKkkrPN', 'Tanzania'),
('sAZfHVBlU0', 'Tayikistán'),
('ob63UAvTJS', 'Timor Oriental'),
('Tf1AMgRqwq', 'Togo'),
('ndvu-oqLpf', 'Tonga'),
('PLQnNx7aq5', 'Trinidad y Tobago'),
('MkpuvYOvPe', 'Túnez'),
('_DHH0bLOdY', 'Turkmenistán'),
('Ku_y2VLGHC', 'Turquía'),
('ZOVi0JXQOs', 'Tuvalu'),
('TAfyaSP_N8', 'Ucrania'),
('V6HAfoOzGL', 'Uganda'),
('eII7OFDTXz', 'Uruguay'),
('25LnNKUYGl', 'Uzbekistán'),
('8JCFHjNwze', 'Vanuatu'),
('blCr0vNXEo', 'Venezuela'),
('E3G2HRl9x2', 'Vietnam'),
('5DpYL7MSd-', 'Yemen'),
('wF87FpoWE0', 'Yibuti'),
('35zloN61lw', 'Zambia'),
('WyYBuP37Ps', 'Zimbabue');

INSERT INTO education (id, name) VALUES
('UWLfRUVGkb', 'Carrera técnica o profesional'),
('HfozUT_PsC', 'Bootcamp'),
('xHgIWbXLUc', 'Libros y Cursos (Udemy, YouTube, Coursera, EdX, etc.)');

INSERT INTO employment_status (id, name) VALUES
('1ievtJUwmI', 'Estudiante'),
('96IXKVy8jH', 'Sin empleo'),
('HDamwxZpk4', 'Trabajo en otra industria'),
('WsAVPNhJNX', 'Trabajo en IT');

INSERT INTO it_field (id, name) VALUES
('MDfP4QzwC8', 'Administración de Bases de Datos'),
('yKQuA2BRIs', 'Análisis de Datos'),
('cj_c51MU8R', 'Análsis funcional'),
('u4n-DcV75D', 'Blockchain'),
('Xhr_B_r60R', 'Ciberseguridad'),
('dd0n-1hzJv', 'Ciencia de Datos'),
('4LgM1z9vVK', 'Computación en la nube'),
('SSU0qrs0Vf', 'Desarrollo de Aplicaciones de Escritorio'),
('FNONFwGW2-', 'Desarrollo de videojuegos'),
('38Rv9pG9nd', 'Desarrollo Móvil'),
('ptd-PqQcOU', 'Desarrollo Web Backend'),
('u4zNpNblrn', 'Desarrollo Web Frontend'),
('8XC3UrEWtq', 'Desarrollo Web FullStack'),
('tR2N5r2BpL', 'DevOps'),
('L1QDjzwdHM', 'Diseño UX/UI'),
('VJNrSbFNbH', 'Gestión de proyectos'),
('ZNnhHga0-z', 'Inteligencia artificial'),
('qlHDp52sF_', 'Machine Learning'),
('fsvtQsinbU', 'QC/QA'),
('5-l1cCC4vu', 'Redes'),
('-Ofa7YVQ6I', 'Web Scraping');

INSERT INTO "language" (id, name) VALUES
('R0mTsUhxr_', 'Alemán'),
('pF3yNwyvis', 'Amárico'),
('8QplyXt3or', 'Árabe argelino'),
('nybjGdYiKP', 'Árabe egipcio'),
('pvTY65u5-l', 'Árabe estándar moderno'),
('VxKW7DPjz4', 'Árabe sudanés'),
('cpBgC99lzo', 'Bengalí'),
('rJY_k7sZPe', 'Bhoshpuri'),
('klHT2DSTYG', 'Birmano'),
('BZLqWY-kmi', 'Canarés'),
('A76fSZhEes', 'Chino hakka'),
('PTs7tkOs9c', 'Chino jin'),
('at4hZ1EG-y', 'Chino mandarín'),
('ejmGm9FlBK', 'Chino Mǐn Nán'),
('JQwzG0gpzS', 'Chino Wu'),
('ctJPVLrsSW', 'Chino yue (incluye Cantonés)'),
('f9Xd80Af_v', 'Coreano'),
('GmF16qvoh5', 'Español'),
('zMnto3e8tN', 'Francés'),
('QbeKU1nXg4', 'Guyarati'),
('KRdZHUPyV7', 'Hausa'),
('oC9n3BurDY', 'Indonesio'),
('l9lAYRxFq4', 'Indostánico (hindi estándar, urdu)'),
('2to_l2lsq-', 'Inglés'),
('cWUxjmxWuM', 'Italiano'),
('HQlxuZdUb7', 'Japonés'),
('8yW7-EK3fq', 'Javanés'),
('0yXLxz027G', 'Lingala'),
('opjokJNYpt', 'Maratí'),
('7_9RTrEjbu', 'Panyabí occidental'),
('SqBJIXvs5J', 'Panyabí'),
('KTMDL1OZsZ', 'Persa iraní'),
('vyBj23iw-D', 'Polaco'),
('GqaQOGgr6H', 'Portugués'),
('YNHPpIUyN0', 'Ruso'),
('8KJAd3f2Wz', 'Suajili'),
('Tvu2iNrslT', 'Tagalo'),
('RhI2eEE46m', 'Tailandés'),
('QlWHkAota6', 'Tamil'),
('qi_Lfq3fHz', 'Telugú'),
('2xgA55Im1G', 'Turco'),
('YDP0tpfKSM', 'Urdu'),
('8Oc06O8lCU', 'Vietnamita'),
('f0cZqOx-Lt', 'Yoruba');

INSERT INTO pronoun (id, name) VALUES
('X_cRRyLmCz', 'él'),
('CDh1hg1KkW', 'ella'),
('vPWAO-ofrt', 'él/ella'),
('XKcoEKN2uw', 'otro'),
('RzIUai6HWL', 'no especifica');

INSERT INTO report_action (id, name) VALUES
('toUoxwUTrg', 'Desactiva cuenta'),
('J9s14lchjO', 'Desestima reporte'),
('b5lHGSAcTV', 'Elimina comentario'),
('rIDwcR6GbB', 'Elimina publicación'),
('4BhmLIjTLQ', 'Silencia usuario');

INSERT INTO "report_reason" (id, name) VALUES
('FWLo2VXNHE', 'Spam'),
('a90dtRdfEP', 'Contenido inapropiado'),
('QSz3vzQtz2', 'Acoso'),
('ASU6wJFZJ8', 'Otro');

INSERT INTO "report_type" (id, name) VALUES
('eXx8aFdM6E', 'Publicación'),
('FciMP7nq18', 'Comentario'),
('aSRB2RNW9K', 'Usuario');

INSERT INTO "role" (id, name) VALUES
('iBM3mRqi3F', 'administrador'),
('8h5NIrFj4K', 'moderador'),
('2SbUCqylYo', 'usuario');

INSERT INTO social_network (id, name) VALUES
('_KWsOph1Qr', 'behance'),
('t6StFTqu_g', 'dribble'),
('7jstZPmPng', 'linkedin'),
('ep54y-_428', 'github'),
('ETuKNg4oot', 'web personal');

INSERT INTO technology (id, name) VALUES
('PvBVCscP0n', '.NET'),
('xgo2DY83a5', 'Angular.js'),
('x5WNYy3dzB', 'C'),
('MvqkJXD9qf', 'C#'),
('DqjOS2k0mx', 'C++'),
('_mnxA7nz8c', 'CSS'),
('Z72uD58Xwn', 'Django'),
('rjxKjNMxay', 'Docker'),
('036xmBG9c7', 'Express.js'),
('P8VB6O_N4O', 'FastAPI'),
('o5QMNUpshP', 'Flask'),
('9XlOiQq80M', 'Git'),
('aWWTfXi741', 'GitHub'),
('cdNhaefY5W', 'Go'),
('xeihZzY2mL', 'Golang'),
('XXZROnTUjP', 'HTML'),
('QhKk9l1Fhr', 'Java'),
('_84RNpgyTx', 'Javascript'),
('n2u7DOmxah', 'Jest'),
('5ZEpJKZV47', 'Kotlin'),
('xEDu_l6J8p', 'Kubernetes'),
('26b6GVbDZf', 'Laravel'),
('FEGZwwLIN4', 'Matlab'),
('3GL4zuCJix', 'MongoDB'),
('I13rLZULz9', 'Nest.js'),
('TUGS1Z5izO', 'Node.js'),
('B7arQIaop_', 'Perl'),
('2I8Q4leKhM', 'PHP'),
('50ecu8Q6OZ', 'Python'),
('5-ST4H3u8R', 'R'),
('5jGWi7r4Z9', 'React.js'),
('Yu9Z4_jnpY', 'Redis'),
('zjgBnU7Xkt', 'Ruby'),
('fU90OeYqSK', 'Ruby on Rails'),
('BMqEtSEy-h', 'Rust'),
('cOb9lGFZOR', 'Scala'),
('oIYPxiJ0-o', 'Spring'),
('FUuPq-qBsx', 'SQL'),
('121bcFfPXf', 'StoryBook'),
('1oCUvjJGGn', 'Swift'),
('UhEGbr04_n', 'TypeScript'),
('kVrilUMYLX', 'Unity'),
('gQJgY5AZmi', 'Vue.js');

INSERT INTO "user"
(id, username, avatar_url, email, password, birthdate)
VALUES
('KrMUeta4ji', 'Eliseo', 'https://docs.material-tailwind.com/img/face-2.jpg', 'eliseus@gmail.com', '12345678', '1990-08-25'),
('h3dk3dO7A_', 'Jayne_Kuhic', 'https://docs.material-tailwind.com/img/face-3.jpg', 'janedoe@gmail.com', '12345678', '1993-05-19'),
('sYfjpcR8ge', 'Nikita', 'https://docs.material-tailwind.com/img/face-4.jpg', 'nikita123@gmail.com', '12345678', '1985-12-04');

CREATE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_updated_at
    BEFORE UPDATE
    ON
        "user"
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER update_aspect_updated_at
    BEFORE UPDATE
    ON
        aspect
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();