INSERT INTO category (name) VALUES
("Proyectos grupales"),
("Hojas de vida"),
("Portafolios"),
("Ofertas de trabajo"),
("Grupos de estudio"),
("Sugerencias de cursos");

INSERT INTO country (name) VALUES
('Afganistán'),
('Albania'),
('Alemania'),
('Andorra'),
('Angola'),
('Antigua y Barbuda'),
('Arabia Saudita'),
('Argelia'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaiyán'),
('Bahamas'),
('Bangladés'),
('Barbados'),
('Baréin'),
('Bélgica'),
('Belice'),
('Benín'),
('Bielorrusia'),
('Birmania'),
('Bolivia'),
('Bosnia y Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunéi'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Bután'),
('Cabo Verde'),
('Camboya'),
('Camerún'),
('Canadá'),
('Catar'),
('Chad'),
('Chile'),
('China'),
('Chipre'),
('Ciudad del Vaticano'),
('Colombia'),
('Comoras'),
('Corea del Norte'),
('Corea del Sur'),
('Costa de Marfil'),
('Costa Rica'),
('Croacia'),
('Cuba'),
('Dinamarca'),
('Dominica'),
('Ecuador'),
('Egipto'),
('El Salvador'),
('Emiratos Árabes Unidos'),
('Eritrea'),
('Eslovaquia'),
('Eslovenia'),
('España'),
('Estados Unidos'),
('Estonia'),
('Etiopía'),
('Filipinas'),
('Finlandia'),
('Fiyi'),
('Francia'),
('Gabón'),
('Gambia'),
('Georgia'),
('Ghana'),
('Granada'),
('Grecia'),
('Guatemala'),
('Guinea'),
('Guinea-Bisáu'),
('Guinea Ecuatorial'),
('Guyana'),
('Haití'),
('Honduras'),
('Hungría'),
('India'),
('Indonesia'),
('Irak'),
('Irán'),
('Irlanda'),
('Islandia'),
('Islas Marshall'),
('Islas Salomón'),
('Israel'),
('Italia'),
('Jamaica'),
('Japón'),
('Jordania'),
('Kazajistán'),
('Kenia'),
('Kirguistán'),
('Kiribati'),
('Kuwait'),
('Laos'),
('Lesoto'),
('Letonia'),
('Líbano'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Lituania'),
('Luxemburgo'),
('Macedonia del Norte'),
('Madagascar'),
('Malasia'),
('Malaui'),
('Maldivas'),
('Malí'),
('Malta'),
('Marruecos'),
('Mauricio'),
('Mauritania'),
('México'),
('Micronesia'),
('Moldavia'),
('Mónaco'),
('Mongolia'),
('Montenegro'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Nicaragua'),
('Níger'),
('Nigeria'),
('Noruega'),
('Nueva Zelanda'),
('Omán'),
('Países Bajos'),
('Pakistán'),
('Palaos'),
('Panamá'),
('Papúa Nueva Guinea'),
('Paraguay'),
('Perú'),
('Polonia'),
('Portugal'),
('Reino Unido'),
('República Centroafricana'),
('República Checa'),
('República del Congo'),
('República Democrática del Congo'),
('República Dominicana'),
('Ruanda'),
('Rumanía'),
('Rusia'),
('Samoa'),
('San Cristóbal y Nieves'),
('San Marino'),
('San Vicente y las Granadinas'),
('Santa Lucía'),
('Santo Tomé y Príncipe'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leona'),
('Singapur'),
('Siria'),
('Somalia'),
('Sri Lanka'),
('Suazilandia'),
('Sudáfrica'),
('Sudán'),
('Sudán del Sur'),
('Suecia'),
('Suiza'),
('Surinam'),
('Tailandia'),
('Taiwán'),
('Tanzania'),
('Tayikistán'),
('Timor Oriental'),
('Togo'),
('Tonga'),
('Trinidad y Tobago'),
('Túnez'),
('Turkmenistán'),
('Turquía'),
('Tuvalu'),
('Ucrania'),
('Uganda'),
('Uruguay'),
('Uzbekistán'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Yibuti'),
('Zambia'),
('Zimbabue');

INSERT INTO education (name) VALUES
("Carrera técnica o profesional"),
("Bootcamp"),
("Libros y Cursos (Udemy, YouTube, Coursera, EdX, etc.)");

INSERT INTO category (name) VALUES
("Estudiante"),
("Sin empleo"),
("Trabajo en otra industria"),
("Trabajo en IT");

INSERT INTO it_field (name) VALUES
('Administración de Bases de Datos'),
('Análisis de Datos'),
('Análsis funcional'),
('Blockchain'),
('Ciberseguridad'),
('Ciencia de Datos'),
('Computación en la nube'),
('Desarrollo de Aplicaciones de Escritorio'),
('Desarrollo de videojuegos'),
('Desarrollo Móvil'),
('Desarrollo Web Backend'),
('Desarrollo Web Frontend'),
('Desarrollo Web FullStack'),
('DevOps'),
('Diseño UX/UI'),
('Gestión de proyectos'),
('Inteligencia artificial'),
('Machine Learning'),
('QC/QA'),
('Redes'),
('Web Scraping');

INSERT INTO language (name) VALUES
('Alemán'),
('Amárico'),
('Árabe argelino'),
('Árabe egipcio'),
('Árabe estándar moderno'),
('Árabe sudanés'),
('Bengalí'),
('Bhoshpuri'),
('Birmano'),
('Canarés'),
('Chino hakka'),
('Chino jin'),
('Chino mandarín'),
('Chino Mǐn Nán'),
('Chino Wu'),
('Chino yue (incluye Cantonés)'),
('Coreano'),
('Español'),
('Francés'),
('Guyarati'),
('Hausa'),
('Indonesio'),
('Indostánico (hindi estándar, urdu)'),
('Inglés'),
('Italiano'),
('Japonés'),
('Javanés'),
('Lingala'),
('Maratí'),
('Panyabí occidental'),
('Panyabí'),
('Persa iraní'),
('Polaco'),
('Portugués'),
('Ruso'),
('Suajili'),
('Tagalo'),
('Tailandés'),
('Tamil'),
('Telugú'),
('Turco'),
('Urdu'),
('Vietnamita'),
('Yoruba');

INSERT INTO pronouns (name) VALUES
("Él"),
("Ella"),
("Él/Ella"),
("Otro"),
("No especifica");

INSERT INTO report_action (name) VALUES
("Desactiva cuenta"),
("Desestima reporte"),
("Elimina comentario"),
("Elimina publicación"),
("Silencia usuario");

INSERT INTO roles (name) VALUES
("administrador")
("moderador"),
("usuario");

INSERT INTO category (name) VALUES
("behance"),
("dribble"),
("linkedin"),
("github"),
("web personal");

INSERT INTO category (name) VALUES
('.NET'),
('Angular.js'),
('C'),
('C#'),
('C++'),
('CSS'),
('Django'),
('Docker'),
('Express.js'),
('FastAPI'),
('Flask'),
('Git'),
('GitHub'),
('Go'),
('Golang'),
('HTML'),
('Java'),
('Javascript'),
('Jest'),
('Kotlin'),
('Kubernetes'),
('Laravel'),
('Matlab'),
('MongoDB'),
('Nest.js'),
('Node.js'),
('Perl'),
('PHP'),
('Python'),
('R'),
('React.js'),
('Redis'),
('Ruby'),
('Ruby on Rails'),
('Rust'),
('Scala'),
('Spring'),
('SQL'),
('StoryBook'),
('Swift'),
('TypeScript'),
('Unity'),
('Vue.js');

CREATE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE
    ON
        users
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE
    ON
        users
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER update_posts_updated_at
    BEFORE UPDATE
    ON
        posts
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER update_comments_updated_at
    BEFORE UPDATE
    ON
        comments
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();